apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: debionetwork-deployment
  labels:
    app: debionetwork
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debionetwork
  serviceName: "debionetwork"
  template:
    metadata:
      labels:
        app: debionetwork
    spec:
      containers:
        - name: debionetwork-node
          image: us-central1-docker.pkg.dev/octopus-prod/octopus-appchains/debio-node@sha256:e2de249c3126bb6930851e6e7fcc6053519d60580c5a9e52a0759cbb6fa1032f
          securityContext:
            runAsUser: 0
          command: ["debio"]
          args:
            - "--base-path=/data"
            - "--chain=octopus-mainnet"
            - "--rpc-external"
            - "--rpc-cors=all"
            - "--rpc-methods=Unsafe"
            - "--validator"
            - "--prometheus-external"
            - "--enable-offchain-indexing=true"
            - "--telemetry-url=wss://telemetry.testnet.octopus.network/submit 0"
          env:
            - name: RUST_LOG
              value: "beefy"
          ports:
            - containerPort: 9933
              name: http
            - containerPort: 30333
              name: p2p
            - containerPort: 9615
              name: metrics
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 64Gi
---
apiVersion: v1
kind: Service
metadata:
  name: debionetwork-service
  labels:
    app: debionetwork
spec:
  type: LoadBalancer
  ports:
  - port: 30333
    targetPort: 30333
    name: p2p
  - port: 9933
    targetPort: 9933
    name: http
  selector:
    app: debionetwork
